announcements/urls.py
#encoding=utf-8
from django.conf.urls import patterns, url
from django.views.generic import ListView
from views import  AnnouncementDetailView,  AddAnnouncementPreview, AnnouncementUpdateView, AnnouncementListView
from forms import AddAnnouncementForm
from models import Announcement
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^$', AnnouncementListView.as_view()),
    url(r'^pateikti/$', login_required(login_url='/nariai/prisijungti')(AddAnnouncementPreview(AddAnnouncementForm))),                        
    url(r'^(?P<pk>\d+)/$', AnnouncementDetailView.as_view()),
    url(r'^(?P<pk>\d+)/redaguoti/$', AnnouncementUpdateView.as_view()),
)

nylithuanian/urls.py
#encoding=utf-8
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView, CreateView
from views import HomeView
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'nylithuanian.views.home', name='home'),
    # url(r'^nylithuanian/', include('nylithuanian.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^$', HomeView.as_view()),
    url(r'^home/', RedirectView.as_view(url='/')),
    url(r'^stop/$', TemplateView.as_view(template_name = 'stop.html')),
    url(r'^nuotraukos/', include('photos.urls'), {'active_tab': 'nuotraukos'}),
    url(r'^skelbimai/', include('classifieds.urls'), {'active_tab': 'skelbimai'}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^renginiai/', include('events.urls'), {'active_tab': 'renginiai'}),
    url(r'^straipsniai/', include('articles.urls'), {'active_tab': 'straipsniai'}),
    url(r'^pranesimai/', include('announcements.urls'), {'active_tab': 'pranesimai'}),
    url(r'^nariai/', include('users.urls')),
    url(r'^naujienlaiskiai/', include('newsletters.urls')),
#    url(r'^(?P<active_tab>sveikinimai)/', include('greetings.urls')),
#    url(r'^(?P<active_tab>uzuojautos)/', include('sympathies.urls')),
    url(r'^media/(?P<path>.*)/$', 'django.views.static.serve', { 'document_root' : settings.MEDIA_ROOT }),
                       
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Apie mus section
urlpatterns += patterns('',
    url(r'^apie-mus/$', TemplateView.as_view(template_name='flatpages/about_us.html'), { 'active_tab': 'apie-mus' }),
    url(r'^apie-mus/susitelkimo-centrai/$', TemplateView.as_view(template_name='flatpages/susitelkimo_centrai.html'), { 'active_tab': 'apie-mus', 'active_item': 'susitelkimo-centrai' }),
    url(r'^apie-mus/apie-jav-lb/$', TemplateView.as_view(template_name='flatpages/apie_jav_lb.html'), { 'active_tab': 'apie-mus', 'active_item': 'apie-jav-lb' }),
    url(r'^apie-mus/prisijunk/$', TemplateView.as_view(template_name='flatpages/prisijunk.html'), { 'active_tab': 'apie-mus', 'active_item': 'prisijunk' }),
    url(r'^apie-mus/parama/$', TemplateView.as_view(template_name = 'flatpages/parama.html'), {'active_tab': 'apie-mus', 'active_item': 'parama'}),
    url(r'^apie-mus/apygarda/$', TemplateView.as_view(template_name='flatpages/apygarda.html'), { 'active_tab': 'apie-mus', 'active_item': 'apygarda' }),
    url(r'^apie-mus/long-island-apylinke/$', TemplateView.as_view(template_name='flatpages/li.html'), { 'active_tab': 'apie-mus', 'active_item': 'li' }),
    url(r'^apie-mus/new-york-miesto-apylinke/$', TemplateView.as_view(template_name='flatpages/nyc.html'), { 'active_tab': 'apie-mus', 'active_item': 'nyc' }),
    url(r'^apie-mus/rytinio-long-island-apylinke/$', TemplateView.as_view(template_name='flatpages/rli.html'), { 'active_tab': 'apie-mus', 'active_item': 'rli' }),
    url(r'^apie-mus/rochester-apylinke/$', TemplateView.as_view(template_name='flatpages/rochester.html'), { 'active_tab': 'apie-mus', 'active_item': 'rochester' }),
    url(r'^apie-mus/valstybines-organizacijos/$', TemplateView.as_view(template_name='flatpages/valstybines_organizacijos.html'), { 'active_tab': 'apie-mus', 'active_item': 'valstybines' }),
    url(r'^apie-mus/religines-organizacijos/$', TemplateView.as_view(template_name='flatpages/religines_organizacijos.html'), { 'active_tab': 'apie-mus', 'active_item': 'religines' }),
    url(r'^apie-mus/visuomenines-organizacijos/$', TemplateView.as_view(template_name='flatpages/visuomenines_organizacijos.html'), { 'active_tab': 'apie-mus', 'active_item': 'visuomenines' }),
    url(r'^apie-mus/svietimo-organizacijos/$', TemplateView.as_view(template_name='flatpages/svietimo_organizacijos.html'), { 'active_tab': 'apie-mus', 'active_item': 'svietimo' }),
    url(r'^apie-mus/ziniasklaidos-organizacijos/$', TemplateView.as_view(template_name='flatpages/ziniasklaidos_organizacijos.html'), { 'active_tab': 'apie-mus', 'active_item': 'ziniasklaidos' }),
    url(r'^apie-mus/redakcija/$', TemplateView.as_view(template_name='flatpages/redakcija.html'), { 'active_tab': 'redakcija', 'active_item': 'redakcija' }),
    url(r'^apie-mus/reklama/$', TemplateView.as_view(template_name='flatpages/reklama.html'), { 'active_tab': 'redakcija', 'active_item': 'reklama' }),
    url(r'^apie-mus/pranesk/$', TemplateView.as_view(template_name='flatpages/pranesk.html'), { 'active_tab': 'redakcija', 'active_item': 'pranesk' }),
    url(r'^apie-mus/nuostatos/$', TemplateView.as_view(template_name='flatpages/nuostatos.html'), { 'active_tab': 'redakcija', 'active_item': 'nuostatos' })
)

# Legacy urls
urlpatterns += patterns('',
    url(r'pradzia.html', RedirectView.as_view(url='/')),
    url(r'apie-mus.html', RedirectView.as_view(url='/apie-mus/')),
    url(r'apie-mus/manhattan-apylinke.html', RedirectView.as_view(url='/apie-mus/new-york-miesto-apylinke/')),
    url(r'apie-mus/brooklyn-queens-apylinke.html', RedirectView.as_view(url='/apie-mus/new-york-miesto-apylinke/')),
    url(r'apie-mus/new-york-miesto-apylinke.html', RedirectView.as_view(url='/apie-mus/new-york-miesto-apylinke/')),
    url(r'apie-mus/rytinio-long-island-apylinke.html', RedirectView.as_view(url='/apie-mus/rytinio-long-island-apylinke/')),
    url(r'apie-mus/long-island-apylinke.html', RedirectView.as_view(url='/apie-mus/long-island-apylinke/')),
    url(r'apie-mus/rochester-apylinke.html', RedirectView.as_view(url='/apie-mus/rochester-apylinke/')),
    url(r'apie-mus/portalo-komanda.html', RedirectView.as_view(url='/apie-mus/redakcija/')),
    
    url(r'renginiai.html', RedirectView.as_view(url='/renginiai/')),
    url(r'komentarai.html', RedirectView.as_view(url='/')),
    url(r'straipsniai.html', RedirectView.as_view(url='/straipsniai/')),
    url(r'pranesimai.html', RedirectView.as_view(url='/pranesimai/')),
    url(r'lietuva-apie-mus.html', RedirectView.as_view(url='/straipsniai/')),
    
    url(r'nuotraukos.html', RedirectView.as_view(url='/nuotraukos/')),
    url(r'nuotraukos/2009.html', RedirectView.as_view(url='/nuotraukos/')),
    url(r'nuotraukos/2010.html', RedirectView.as_view(url='/nuotraukos/')),
    url(r'nuotraukos/2011.html', RedirectView.as_view(url='/nuotraukos/')),
    url(r'nuotraukos/2012.html', RedirectView.as_view(url='/nuotraukos/')),
    url(r'nuotraukos/2013-m.html', RedirectView.as_view(url='/nuotraukos/')),
    
    url(r'skelbimai.html', RedirectView.as_view(url='/skelbimai/')),
    url(r'skelbimai/ikelti-skelbima.html', RedirectView.as_view(url='/skelbimai/pateikti/')),
    url(r'skelbimai/skelbimu-sarasas.html', RedirectView.as_view(url='/skelbimai/')),
    
    url(r'login.html', RedirectView.as_view(url='/nariai/prisijungti/')),
    url(r'login/register-user.html', RedirectView.as_view(url='/nariai/registruotis/')),
    url(r'login/saskaita.html', RedirectView.as_view(url='/nariai/prisijungti/')),
)

photos/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import *


urlpatterns = patterns('',
                       url(r'^$', GalleryListView.as_view()),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$', GalleryDateDetailView.as_view()),
                       url(r'^gallery/pateikti/$', login_required(login_url='/nariai/prisijungti')(GalleryCreateView.as_view())),
                       url(r'^gallery/page/(?P<page>[0-9]+)/$', GalleryListView.as_view()),
                        url(r'^gallery/(?P<slug>[\-\d\w]+)/$', GalleryDetailView.as_view()),
                        url(r'^gallery/(?P<slug>[\-\d\w]+)/keisti-eiliskuma/$', login_required(login_url='/nariai/prisijungti')(GalleryReorderView.as_view())),
                        url(r'^gallery/(?P<slug>[\-\d\w]+)/redaguoti/$', login_required(login_url='/nariai/prisijungti')(GalleryUpdateView.as_view())),
                                                
                       )

urlpatterns += patterns('',
                        url(r'^photo/sort-photos/$', sort_photos),
                        url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                            PhotoDateDetailView.as_view()),
                        url(r'^photo/page/(?P<page>[0-9]+)/$', PhotoListView.as_view()),
                        url(r'^photo/pateikti/$',
                            login_required(login_url='/nariai/prisijungti')(PhotoCreateView.as_view())),
                        url(r'^photo/(?P<slug>[\-\d\w]+)/redaguoti/$',
                            login_required(login_url='/nariai/prisijungti')(PhotoUpdateView.as_view())),

                        url(r'^photo/pateikti-daug/$',
                             login_required(login_url='/nariai/prisijungti')(BulkPhotoUploadView.as_view())),
                        url(r'^photo/(?P<slug>[\-\d\w]+)/$', PhotoDetailView.as_view()),
                        )

urlpatterns += patterns('',
                        url(r'^renginys/(?P<pk>[\d]+)/$', EventPhotoListView.as_view()),
                        )


# url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$', GalleryDayArchiveView.as_view(), name='pl-gallery-archive-day'),
# url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/$', GalleryMonthArchiveView.as_view(), name='pl-gallery-archive-month'),
# url(r'^gallery/(?P<year>\d{4})/$', GalleryYearArchiveView.as_view(), name='pl-gallery-archive-year'),
# url(r'^photo/$', PhotoArchiveIndexView.as_view(), name='pl-photo-archive'),
# url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$', PhotoDayArchiveView.as_view(), name='pl-photo-archive-day'),
# url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PhotoMonthArchiveView.as_view(), name='pl-photo-archive-month'),
# url(r'^photo/(?P<year>\d{4})/$', PhotoYearArchiveView.as_view(), name='pl-photo-archive-year'),

users/urls.py
#encoding=utf-8
from django.conf.urls import patterns, url
from django.views.generic import ListView, CreateView, TemplateView
from django.contrib.auth.views import login, logout, password_reset, password_reset_confirm, password_reset_done, password_reset_complete
from django.contrib.auth.decorators import login_required

from models import SiteUser
from forms import RegisterSiteUserForm
from views import SiteUserCreateView, SiteUserDetailView, SiteUserChangePasswordView, SiteUserUpdateView, confirm_registration

urlpatterns = patterns('',
#    url(r'^$', ListView.as_view(model = SiteUser,)),
#    url(r'^mano-saskaita/$', SiteUserPersonalView.as_view()),
    url(r'^pamirsau-slaptazodi/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {
                                                                                                   'template_name': 'users/password_reset_confirm.html',
                                                                                                   'post_reset_redirect': '/nariai/pamirsau-slaptazodi/baigta'
                                                                                                   }),
    url(r'^pamirsau-slaptazodi/baigta/$', password_reset_complete, {
                                                                    'template_name': 'users/password_reset_complete.html'
                                                                    }),
    url(r'^pamirsau-slaptazodi/email/$', password_reset_done, {
                                                               'template_name': 'users/password_reset_done.html'
                                                               }),
    url(r'^pamirsau-slaptazodi/$', password_reset, {
                                                    'template_name': 'users/password_reset_form.html',
                                                    'email_template_name': 'emails/password_reset.html',
                                                    'subject_template_name': 'emails/password_reset_subject.txt',
                                                    'post_reset_redirect': '/nariai/pamirsau-slaptazodi/email'
                                                    }),
    url(r'^registruotis/$', SiteUserCreateView.as_view()),
    url(r'^registruotis/priimta/$', TemplateView.as_view(template_name = 'users/registration_accepted.html',)),
    url(r'^patvirtinti/(?P<username>\S+)/(?P<registrationHash>\S+)/$', confirm_registration),
    url(r'^prisijungti/$', login, {
                                   'template_name' : 'users/login.html',
                                   }),
    url(r'^atsijungti/$', logout, { 'next_page' : '/', }),
    url(r'^(?P<slug>\S+)/keisti-slaptazodi/$', login_required(login_url='/nariai/prisijungti')(SiteUserChangePasswordView.as_view())),
    url(r'^(?P<slug>\S+)/redaguoti/$', login_required(login_url='/nariai/prisijungti')(SiteUserUpdateView.as_view())),
    url(r'^(?P<slug>\S+)/$', SiteUserDetailView.as_view()),
)

announcements/models.py
#encoding=utf-8
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import RegexValidator
from django.conf import settings

class PublicAnnouncementsManager(models.Manager):
    def get_query_set(self):
        return super(PublicAnnouncementsManager, self).get_query_set().filter(is_approved=True)
    
class Announcement(models.Model):
    user = models.ForeignKey(User, related_name='user+', null=False, blank=False, editable=False) # user who created the post; only that user can edit or delete it
    title = models.CharField(null=False, blank=False, max_length=255, verbose_name='Pavadinimas')
    body = models.TextField(null=False, blank=False, verbose_name='Pranešimo tekstas', help_text='Tekstas turi būti rašomas naudojant <a target="_blank" href="http://en.wikipedia.org/wiki/Textile_%28markup_language%29">Textile</a> žymėjimo kalbą.')
    first_name = models.CharField(null=False, blank=True, max_length=30, verbose_name="Autoriaus vardas")
    last_name = models.CharField(null=False, blank=True, max_length=30, verbose_name="Autoriaus pavardė")
    organization_title = models.CharField(null=False, blank = True, max_length = 100, verbose_name="Organizacijos pavadinimas", help_text="Organizacija, kuriai priklauso autorius") # if the user is an organization, its title
    signature = models.CharField(null=False, blank=True, max_length=255, verbose_name="Autoriaus parašas", help_text="Papildoma informacija apie autorių") 
    phone_number = models.CharField(null=False, blank=True, max_length = 20, verbose_name="Telefono numeris", help_text="Autoriaus telefono numeris", validators=[RegexValidator(r'^[-0-9+() ]*$')])
    email_address = models.EmailField(null=False, blank=True, verbose_name="El. pašto adresas", help_text="Autoriaus elektroninio pašto adresas")
    create_date = models.DateTimeField(null=False, auto_now_add=True, verbose_name='Pranešimo ikelimo data', help_text='Prašome datą įvesti formatu "yyyy-mm-dd hh:mm"')
    modify_date = models.DateTimeField(null=False, auto_now=True, verbose_name='Pranešimo paskutinio redagavimo data', help_text='Prašome datą įvesti formatu "yyyy-mm-dd hh:mm"')
    is_approved = models.BooleanField(null=False, blank=False, default = False) # only approved announcements will ever be shown publicly; only administrator can change this value
    
    objects = models.Manager()
    public = PublicAnnouncementsManager()
    
    class Meta:
        db_table = 'announcements'
    
    def __unicode__(self):
        return self.title
    
    def get_absolute_url(self):
        return settings.SITE_URL + '/pranesimai/{0}'.format(self.id)

announcements/forms.py
#encoding=utf-8
from django.forms import ModelForm, Textarea, TextInput
from models import Announcement

class AnnouncementForm(ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

class AddAnnouncementForm(AnnouncementForm):   
    class Meta:
        model = Announcement
        exclude = ('is_approved',)

announcements/templates/announcements/announcement_create.html
{% extends 'announcements/announcement_form.html' %}

{% block title %}Pateikti naują pranešimą{% endblock %}
{% block form_title %}Pateikti naują pranešimą{% endblock %}
{% block submit_button_title %}Peržiūrėti tekstą{% endblock %}

announcements/templates/announcements/announcement_detail.html
{% extends 'base.html' %}
{% load markup %}

{% block title %}{{ announcement.title }}{% endblock %}

{% block content %}
<h1>{% if is_favorite %}<span><img src="{{ STATIC_URL }}images/toolbar/favorite.png" width="32" height="32" title="Favoritas" alt="Favoritas" /></span>{% endif %} {{ announcement.title }}</h1>

{% if announcement.first_name %}
    <p class="meta">
        <b>Autorius:</b> {{ announcement.first_name }} {{ announcement.last_name }}{% if announcement.organization_title %}, {{ announcement.organization_title }}{% endif %}
    </p>
{% endif %}

{% if announcement.phone_number or announcement.email_address %}
    <p class="meta">
        {% if announcement.phone_number %}
            <b>Telefonas:</b> {{ announcement.phone_number }}
        {% endif %}
        {% if announcement.email_address %}
         <b>El. paštas:</b> <a href="mailto:{{ announcement.email_address }}">{{ announcement.email_address }}</a>
        {% endif %}
    </p>
{% endif %}

{% if announcement.signature %}
    <p class="meta">{{ announcement.signature }}</p>
{% endif %}

{{ announcement.body|striptags|textile }}
{% endblock%}

{% block sidebar %}
<div class="box">
    <h2 class="headline">Papildomos funkcijos</h2>
    <ul class="clean">
        <li><img src="{{ STATIC_URL }}images/toolbar/add.png" width="32" height="32" title="Įkelti" alt="Įkelti" /><a href="../pateikti">Pateikti naują pranešimą</a></li>
        {% if user.id == announcement.user_id or user.is_staff %}
        <li><img src="{{ STATIC_URL }}images/toolbar/edit.png" width="32" height="32" title="Redaguoti" alt="Redaguoti" /><a href="redaguoti">Redaguoti</a></li>
        {% endif %}
    </ul>
</div>

<div class="box spacious">
    <p class="action">
        <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=info@nylithuanian.org&item_name=Parama%20JAV%20LB%20Niujorko%20apygardai&item_number=Niujorko%20apygarda&currency_code=USD&image_url=https://www.nylithuanian.org/static/images/logo_paypal.png&amount=5">Patinka ši svetainė?<br />
            Paremk ją $5.00 dovana!</a>
    </p>
    <p class="action">

    </p>
</div>
{% endblock %}

announcements/templates/announcements/announcement_edit.html
{% extends 'announcements/announcement_form.html' %}

{% block title %}Redaguoti pranešimą{% endblock %}
{% block form_title %}Redaguoti pranešimą{% endblock %}  
{% block submit_button_title %}Pateikti pranešimą{% endblock %}

announcements/templates/announcements/announcement_form.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block form_title %}{% endblock %}</h1>
<form action="" method="post" name="form">
    {% csrf_token %}
    {{ form.id }}
    
    {% if form.errors %}
    <p class="error">
        Pranešimo pateikti nepavyko. Atidžiai perskaitykite klaidų pranešimus ir pabandykite dar kartą.
    </p>
	{% endif %}

        <p>Privalomi laukeliai yra <span class="required">paryškinti</span>.</p>
        <fieldset>
            <legend>Pagrindinė informacija</legend>
            <p>
                <label class="{{ form.title.css_classes }}" for="id_title">{{ form.title.label }}</label><br />
                {{ form.title }}
                {% if form.title.errors %}
                    <span class="error">
                        {% for error in form.title.errors %}
                            {{ error }} 
                        {% endfor %}
                    </span>
                {% endif %}
                {% if form.title.help_text %}<br /><span class="helptext">{{form.title.help_text }}</span>{% endif %}
            </p>
            <p>
                <label class="{{ form.body.css_classes }}" for="id_body">{{ form.body.label }}</label><br />
                {{ form.body }}
                {% if form.body.errors %}
                    <span class="error">
                        {% for error in form.body.errors %}
                            {{ error }} 
                        {% endfor %}
                    </span>
                {% endif %}
                {% if form.body.help_text %}<br /><span class="helptext">{{form.body.help_text|safe }}</span>{% endif %}
            </p>
        </fieldset>
        <fieldset>
            <legend>Autoriaus informacija</legend>
            <p>
                <label class="{{ form.first_name.css_classes }}" for="id_first_name">{{ form.first_name.label }}</label><br />
                {{ form.first_name }}
                {% if form.first_name.errors %}
                    <span class="error">
                        {% for error in form.first_name.errors %}
                            {{ error }} 
                        {% endfor %}
                    </span>
                {% endif %}
                {% if form.first_name.help_text %}<br /><span class="helptext">{{form.first_name.help_text }}</span>{% endif %}
            </p>
            <p>
                <label class="{{ form.last_name.css_classes }}" for="id_last_name">{{ form.last_name.label }}</label><br />
                {{ form.last_name }}
                {% if form.last_name.errors %}
                    <span class="error">
                        {% for error in form.last_name.errors %}
                            {{ error }} 
                        {% endfor %}
                    </span>
                {% endif %}
                {% if form.last_name.help_text %}<br /><span class="helptext">{{form.last_name.help_text }}</span>{% endif %}
            </p>
            <p>
                <label class="{{ form.organization_title.css_classes }}" for="id_organization_title">{{ form.organization_title.label }}</label><br />
                {{ form.organization_title }}
                {% if form.organization_title.errors %}
                    <span class="error">
                        {% for error in form.organization_title.errors %}
                            {{ error }} 
                        {% endfor %}
                    </span>
                {% endif %}
                {% if form.organization_title.help_text %}<br /><span class="helptext">{{form.organization_title.help_text }}</span>{% endif %}
            </p>
            <p>
                <label class="{{ form.phone_number.css_classes }}" for="id_phone_number">{{ form.phone_number.label }}</label><br />
                {{ form.phone_number }}
                {% if form.phone_number.errors %}
                    <span class="error">
                        {% for error in form.phone_number.errors %}
                            {{ error }} 
                        {% endfor %}
                    </span>
                {% endif %}
                {% if form.phone_number.help_text %}<br /><span class="helptext">{{form.phone_number.help_text }}</span>{% endif %}
            </p>
            <p>
                <label class="{{ form.email_address.css_classes }}" for="id_email_address">{{ form.email_address.label }}</label><br />
                {{ form.email_address }}
                {% if form.email_address.errors %}
                    <span class="error">
                        {% for error in form.email_address.errors %}
                            {{ error }} 
                        {% endfor %}
                    </span>
                {% endif %}
                {% if form.email_address.help_text %}<br /><span class="helptext">{{form.email_address.help_text }}</span>{% endif %}
            </p>
            <p>
                <label class="{{ form.signature.css_classes }}" for="id_signature">{{ form.signature.label }}</label><br />
                {{ form.signature }}
                {% if form.signature.errors %}
                    <span class="error">
                        {% for error in form.signature.errors %}
                            {{ error }} 
                        {% endfor %}
                    </span>
                {% endif %}
                {% if form.signature.help_text %}<br /><span class="helptext">{{form.signature.help_text }}</span>{% endif %}
            </p>
        </fieldset>
  
    <button type="submit" value="Preview" >{% block submit_button_title %}{% endblock %}</button>
    <a class="cancel" href="/">Atšaukti</a>
</form>


{% if form.non_field_errors %}
	<ul class="error">
	    {% for error in form.non_field_errors %}
	    	<li>{{ error }}</li>
	    {% endfor %}
	</ul>
{% endif %}

{% endblock %}

{% block sidebar %}
<div class="box">
    <h2 class="headline">Pranešimo aprašymo pagalba</h2>
    <ul>
        <li>Norėdami pradėti naują pastraipą, įterpkite tuščią eilutę</li>
        <li>Norėdami įterpti pastraipos antraštę, pradėkite naują eilutę simboliais "h2. "</li>
        <li>Norėdami sukurti nenumeruotą sąrašą, pradėkite kiekvieną eilutę simboliais "* "</li>
        <li>Norėdami įterpti numeruotą sąrašą, pradėkite kiekvieną eilutę simboliais "# "</li>
        <li>Norėdami įterpti nuorodą, rašykite "nuorodos tekstas":nuoroda</li>
        <li>Daugiau informacijos ir pavyzdžių rasite <a target="_blank" href="http://en.wikipedia.org/wiki/Textile_%28markup_language%29">Textile svetainėje</a></li>
    </ul>
</div>
{% endblock %}

announcements/templates/announcements/error.html
{% extends 'base.html' %}
{% load markup %}

{% block title %}Klaida{% endblock %}

{% block content %}
<h1>Dėmesio! Įvyko klaida!</h1>

<p>{{ message }}</p>
{% endblock %}