nylithuanian/urls.py
#encoding=utf-8
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView, CreateView
from views import HomeView
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'nylithuanian.views.home', name='home'),
    # url(r'^nylithuanian/', include('nylithuanian.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^$', HomeView.as_view()),
    url(r'^home/', RedirectView.as_view(url='/')),
    url(r'^stop/$', TemplateView.as_view(template_name = 'stop.html')),
    url(r'^nuotraukos/', include('photos.urls'), {'active_tab': 'nuotraukos'}),
    url(r'^skelbimai/', include('classifieds.urls'), {'active_tab': 'skelbimai'}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^renginiai/', include('events.urls'), {'active_tab': 'renginiai'}),
    url(r'^straipsniai/', include('articles.urls'), {'active_tab': 'straipsniai'}),
    url(r'^pranesimai/', include('announcements.urls'), {'active_tab': 'pranesimai'}),
    url(r'^nariai/', include('users.urls')),
    url(r'^naujienlaiskiai/', include('newsletters.urls')),
#    url(r'^(?P<active_tab>sveikinimai)/', include('greetings.urls')),
#    url(r'^(?P<active_tab>uzuojautos)/', include('sympathies.urls')),
    url(r'^media/(?P<path>.*)/$', 'django.views.static.serve', { 'document_root' : settings.MEDIA_ROOT }),
                       
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Apie mus section
urlpatterns += patterns('',
    url(r'^apie-mus/$', TemplateView.as_view(template_name='flatpages/about_us.html'), { 'active_tab': 'apie-mus' }),
    url(r'^apie-mus/susitelkimo-centrai/$', TemplateView.as_view(template_name='flatpages/susitelkimo_centrai.html'), { 'active_tab': 'apie-mus', 'active_item': 'susitelkimo-centrai' }),
    url(r'^apie-mus/apie-jav-lb/$', TemplateView.as_view(template_name='flatpages/apie_jav_lb.html'), { 'active_tab': 'apie-mus', 'active_item': 'apie-jav-lb' }),
    url(r'^apie-mus/prisijunk/$', TemplateView.as_view(template_name='flatpages/prisijunk.html'), { 'active_tab': 'apie-mus', 'active_item': 'prisijunk' }),
    url(r'^apie-mus/parama/$', TemplateView.as_view(template_name = 'flatpages/parama.html'), {'active_tab': 'apie-mus', 'active_item': 'parama'}),
    url(r'^apie-mus/apygarda/$', TemplateView.as_view(template_name='flatpages/apygarda.html'), { 'active_tab': 'apie-mus', 'active_item': 'apygarda' }),
    url(r'^apie-mus/long-island-apylinke/$', TemplateView.as_view(template_name='flatpages/li.html'), { 'active_tab': 'apie-mus', 'active_item': 'li' }),
    url(r'^apie-mus/new-york-miesto-apylinke/$', TemplateView.as_view(template_name='flatpages/nyc.html'), { 'active_tab': 'apie-mus', 'active_item': 'nyc' }),
    url(r'^apie-mus/rytinio-long-island-apylinke/$', TemplateView.as_view(template_name='flatpages/rli.html'), { 'active_tab': 'apie-mus', 'active_item': 'rli' }),
    url(r'^apie-mus/rochester-apylinke/$', TemplateView.as_view(template_name='flatpages/rochester.html'), { 'active_tab': 'apie-mus', 'active_item': 'rochester' }),
    url(r'^apie-mus/valstybines-organizacijos/$', TemplateView.as_view(template_name='flatpages/valstybines_organizacijos.html'), { 'active_tab': 'apie-mus', 'active_item': 'valstybines' }),
    url(r'^apie-mus/religines-organizacijos/$', TemplateView.as_view(template_name='flatpages/religines_organizacijos.html'), { 'active_tab': 'apie-mus', 'active_item': 'religines' }),
    url(r'^apie-mus/visuomenines-organizacijos/$', TemplateView.as_view(template_name='flatpages/visuomenines_organizacijos.html'), { 'active_tab': 'apie-mus', 'active_item': 'visuomenines' }),
    url(r'^apie-mus/svietimo-organizacijos/$', TemplateView.as_view(template_name='flatpages/svietimo_organizacijos.html'), { 'active_tab': 'apie-mus', 'active_item': 'svietimo' }),
    url(r'^apie-mus/ziniasklaidos-organizacijos/$', TemplateView.as_view(template_name='flatpages/ziniasklaidos_organizacijos.html'), { 'active_tab': 'apie-mus', 'active_item': 'ziniasklaidos' }),
    url(r'^apie-mus/redakcija/$', TemplateView.as_view(template_name='flatpages/redakcija.html'), { 'active_tab': 'redakcija', 'active_item': 'redakcija' }),
    url(r'^apie-mus/reklama/$', TemplateView.as_view(template_name='flatpages/reklama.html'), { 'active_tab': 'redakcija', 'active_item': 'reklama' }),
    url(r'^apie-mus/pranesk/$', TemplateView.as_view(template_name='flatpages/pranesk.html'), { 'active_tab': 'redakcija', 'active_item': 'pranesk' }),
    url(r'^apie-mus/nuostatos/$', TemplateView.as_view(template_name='flatpages/nuostatos.html'), { 'active_tab': 'redakcija', 'active_item': 'nuostatos' })
)

# Legacy urls
urlpatterns += patterns('',
    url(r'pradzia.html', RedirectView.as_view(url='/')),
    url(r'apie-mus.html', RedirectView.as_view(url='/apie-mus/')),
    url(r'apie-mus/manhattan-apylinke.html', RedirectView.as_view(url='/apie-mus/new-york-miesto-apylinke/')),
    url(r'apie-mus/brooklyn-queens-apylinke.html', RedirectView.as_view(url='/apie-mus/new-york-miesto-apylinke/')),
    url(r'apie-mus/new-york-miesto-apylinke.html', RedirectView.as_view(url='/apie-mus/new-york-miesto-apylinke/')),
    url(r'apie-mus/rytinio-long-island-apylinke.html', RedirectView.as_view(url='/apie-mus/rytinio-long-island-apylinke/')),
    url(r'apie-mus/long-island-apylinke.html', RedirectView.as_view(url='/apie-mus/long-island-apylinke/')),
    url(r'apie-mus/rochester-apylinke.html', RedirectView.as_view(url='/apie-mus/rochester-apylinke/')),
    url(r'apie-mus/portalo-komanda.html', RedirectView.as_view(url='/apie-mus/redakcija/')),
    
    url(r'renginiai.html', RedirectView.as_view(url='/renginiai/')),
    url(r'komentarai.html', RedirectView.as_view(url='/')),
    url(r'straipsniai.html', RedirectView.as_view(url='/straipsniai/')),
    url(r'pranesimai.html', RedirectView.as_view(url='/pranesimai/')),
    url(r'lietuva-apie-mus.html', RedirectView.as_view(url='/straipsniai/')),
    
    url(r'nuotraukos.html', RedirectView.as_view(url='/nuotraukos/')),
    url(r'nuotraukos/2009.html', RedirectView.as_view(url='/nuotraukos/')),
    url(r'nuotraukos/2010.html', RedirectView.as_view(url='/nuotraukos/')),
    url(r'nuotraukos/2011.html', RedirectView.as_view(url='/nuotraukos/')),
    url(r'nuotraukos/2012.html', RedirectView.as_view(url='/nuotraukos/')),
    url(r'nuotraukos/2013-m.html', RedirectView.as_view(url='/nuotraukos/')),
    
    url(r'skelbimai.html', RedirectView.as_view(url='/skelbimai/')),
    url(r'skelbimai/ikelti-skelbima.html', RedirectView.as_view(url='/skelbimai/pateikti/')),
    url(r'skelbimai/skelbimu-sarasas.html', RedirectView.as_view(url='/skelbimai/')),
    
    url(r'login.html', RedirectView.as_view(url='/nariai/prisijungti/')),
    url(r'login/register-user.html', RedirectView.as_view(url='/nariai/registruotis/')),
    url(r'login/saskaita.html', RedirectView.as_view(url='/nariai/prisijungti/')),
)

photos/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import *


urlpatterns = patterns('',
                       url(r'^$', GalleryListView.as_view()),
                       url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$', GalleryDateDetailView.as_view()),
                       url(r'^gallery/pateikti/$', login_required(login_url='/nariai/prisijungti')(GalleryCreateView.as_view())),
                       url(r'^gallery/page/(?P<page>[0-9]+)/$', GalleryListView.as_view()),
                        url(r'^gallery/(?P<slug>[\-\d\w]+)/$', GalleryDetailView.as_view()),
                        url(r'^gallery/(?P<slug>[\-\d\w]+)/keisti-eiliskuma/$', login_required(login_url='/nariai/prisijungti')(GalleryReorderView.as_view())),
                        url(r'^gallery/(?P<slug>[\-\d\w]+)/redaguoti/$', login_required(login_url='/nariai/prisijungti')(GalleryUpdateView.as_view())),
                                                
                       )

urlpatterns += patterns('',
                        url(r'^photo/sort-photos/$', sort_photos),
                        url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                            PhotoDateDetailView.as_view()),
                        url(r'^photo/page/(?P<page>[0-9]+)/$', PhotoListView.as_view()),
                        url(r'^photo/pateikti/$',
                            login_required(login_url='/nariai/prisijungti')(PhotoCreateView.as_view())),
                        url(r'^photo/(?P<slug>[\-\d\w]+)/redaguoti/$',
                            login_required(login_url='/nariai/prisijungti')(PhotoUpdateView.as_view())),

                        url(r'^photo/pateikti-daug/$',
                             login_required(login_url='/nariai/prisijungti')(BulkPhotoUploadView.as_view())),
                        url(r'^photo/(?P<slug>[\-\d\w]+)/$', PhotoDetailView.as_view()),
                        )

urlpatterns += patterns('',
                        url(r'^renginys/(?P<pk>[\d]+)/$', EventPhotoListView.as_view()),
                        )


# url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$', GalleryDayArchiveView.as_view(), name='pl-gallery-archive-day'),
# url(r'^gallery/(?P<year>\d{4})/(?P<month>[a-z]{3})/$', GalleryMonthArchiveView.as_view(), name='pl-gallery-archive-month'),
# url(r'^gallery/(?P<year>\d{4})/$', GalleryYearArchiveView.as_view(), name='pl-gallery-archive-year'),
# url(r'^photo/$', PhotoArchiveIndexView.as_view(), name='pl-photo-archive'),
# url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$', PhotoDayArchiveView.as_view(), name='pl-photo-archive-day'),
# url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PhotoMonthArchiveView.as_view(), name='pl-photo-archive-month'),
# url(r'^photo/(?P<year>\d{4})/$', PhotoYearArchiveView.as_view(), name='pl-photo-archive-year'),

users/urls.py
#encoding=utf-8
from django.conf.urls import patterns, url
from django.views.generic import ListView, CreateView, TemplateView
from django.contrib.auth.views import login, logout, password_reset, password_reset_confirm, password_reset_done, password_reset_complete
from django.contrib.auth.decorators import login_required

from models import SiteUser
from forms import RegisterSiteUserForm
from views import SiteUserCreateView, SiteUserDetailView, SiteUserChangePasswordView, SiteUserUpdateView, confirm_registration

urlpatterns = patterns('',
#    url(r'^$', ListView.as_view(model = SiteUser,)),
#    url(r'^mano-saskaita/$', SiteUserPersonalView.as_view()),
    url(r'^pamirsau-slaptazodi/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {
                                                                                                   'template_name': 'users/password_reset_confirm.html',
                                                                                                   'post_reset_redirect': '/nariai/pamirsau-slaptazodi/baigta'
                                                                                                   }),
    url(r'^pamirsau-slaptazodi/baigta/$', password_reset_complete, {
                                                                    'template_name': 'users/password_reset_complete.html'
                                                                    }),
    url(r'^pamirsau-slaptazodi/email/$', password_reset_done, {
                                                               'template_name': 'users/password_reset_done.html'
                                                               }),
    url(r'^pamirsau-slaptazodi/$', password_reset, {
                                                    'template_name': 'users/password_reset_form.html',
                                                    'email_template_name': 'emails/password_reset.html',
                                                    'subject_template_name': 'emails/password_reset_subject.txt',
                                                    'post_reset_redirect': '/nariai/pamirsau-slaptazodi/email'
                                                    }),
    url(r'^registruotis/$', SiteUserCreateView.as_view()),
    url(r'^registruotis/priimta/$', TemplateView.as_view(template_name = 'users/registration_accepted.html',)),
    url(r'^patvirtinti/(?P<username>\S+)/(?P<registrationHash>\S+)/$', confirm_registration),
    url(r'^prisijungti/$', login, {
                                   'template_name' : 'users/login.html',
                                   }),
    url(r'^atsijungti/$', logout, { 'next_page' : '/', }),
    url(r'^(?P<slug>\S+)/keisti-slaptazodi/$', login_required(login_url='/nariai/prisijungti')(SiteUserChangePasswordView.as_view())),
    url(r'^(?P<slug>\S+)/redaguoti/$', login_required(login_url='/nariai/prisijungti')(SiteUserUpdateView.as_view())),
    url(r'^(?P<slug>\S+)/$', SiteUserDetailView.as_view()),
)

users/forms.py
#encoding=utf-8
from django import forms
from django.forms import PasswordInput, RadioSelect
from django.template.loader import get_template
from django.template import Context
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, RegexValidator
from django.contrib.auth.forms import PasswordChangeForm

from .models import SiteUser
from .validators import *

class RegisterSiteUserForm(forms.ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'
    password = forms.CharField(
                               label='Slaptažodis',
                               max_length=128,
                               help_text='Slaptažodis turi būti mažiausiai 8 simbolių.',
                               widget=PasswordInput,
                               validators=[
                                           MinLengthValidator(8),
                                           validate_uncommon_word,
                                           ]
                               )
    confirm_password = forms.CharField(label='Slaptažodis (pakartoti)', max_length=128, widget=PasswordInput)
    email = forms.EmailField(label='El. pašto adresas', required=True)
    
    class Meta:
        model = SiteUser
        fields = ('username', 'password', 'confirm_password', 'email')
        
    def clean(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('confirm_password')
        if password1 and password1 != password2:
            raise ValidationError(u'Įvestos slaptažodžių reikšmės nesutampa.')
        return super(RegisterSiteUserForm, self).clean()
    
    def save(self):
        
        siteUser = super(RegisterSiteUserForm, self).save()
        
        # E-mail user to confirm registration
        plainText = get_template('emails/reg_confirm_email.txt')
        htmlText = get_template('emails/reg_confirm_email.html')
        subject = u'Prašome patvirtinti registraciją'
        c = Context({
                     'username' : siteUser.username,
                     'registration_hash' : siteUser.temp_hash,
                     'SITE_URL': settings.SITE_URL,
                     })
        
        
        msg = EmailMultiAlternatives(subject, plainText.render(c), settings.SERVER_EMAIL, (siteUser.email, ))
        msg.attach_alternative(htmlText.render(c), 'text/html')
        msg.send()
        
        return siteUser
    

class SiteUserPasswordChangeForm(PasswordChangeForm):
    new_password1 = forms.CharField(
                               label='Slaptažodis',
                               max_length=128,
                               help_text='Slaptažodis turi būti mažiausiai 8 simbolių.',
                               widget=PasswordInput,
                               validators=[
                                           MinLengthValidator(8),
                                           validate_uncommon_word,
                                           ]
                               )

class PromoteUserForm(forms.Form):
    USER_TYPES = (
                  ('regular', 'Regular User'),
                  ('admin', 'Administrator'),
                  ('staff', 'Staff Member'),
                  ('photographer', 'Photographer'),
                  ('journalist', 'Journalist'),
                  )
    username = forms.CharField(max_length = 30, label='Vartotojo vardas')
    user_type = forms.ChoiceField(choices = USER_TYPES, label='Vartotojo tipas')
  
class EditSiteUserForm(forms.ModelForm):
    class Meta:
        model = SiteUser
        widgets = {
                   'is_subscribed': RadioSelect(),
                   }
        exclude = ('username', 'password', 'email', 'last_login', 'date_joined', 'is_superuser', 'is_active', 'is_staff')
        

users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Prisijunk prie mūsų{% endblock %}

{% block content %}
    <h2>Prisijunk prie mūsų!</h2>
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
        <p>
            <label for="id_username">Vartotojo vardas<abbr title="Required">*</abbr></label><br/>
            {{ form.username }}
            {% if form.username.errors %}
                <span class="error">
                    {% for error in form.username.errors %}
                        {{ error }} 
                    {% endfor %}
                </span>
            {% endif %}
        </p>
        <p>
            <label for="id_password">Slaptažodis<abbr title="Required">*</abbr></label><br/>
            {{ form.password }}
            {% if form.password.errors %}
                <span class="error">
                    {% for error in form.password.errors %}
                        {{ error }} 
                    {% endfor %}
                </span>
            {% endif %}
        </p>
        <button type="submit" value="login">Prisijungti</button>
        <a class="cancel" href="/nariai/registruotis">Registruotis</a>
        <a class="cancel" href="/nariai/pamirsau-slaptazodi">Pamiršau slaptažodį</a><br />
    </form>
    {% if form.errors %}
        <p class="error">
            Prisijungti nepavyko. Atidžiai perskaitykite klaidų pranešimus ir pabandykite dar kartą.
        </p>
        {% if form.non_field_errors %}
            <ul class="error">
                {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endif %}

    
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Slaptažodis pakeistas sėkmingai{% endblock %}

{% block content %}
<h1>Sveikiname!</h1>

<p>Tavo slaptažodis pakeistas sėkmingai. Kviečiame
	<a title="Prisijungti" href="/nariai/prisijungti/">prisijungti</a>!</p>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Sukurti naują slaptažodį{% endblock %}

{% block content %}
    {% if validlink %}
        <p>Siekdami saugumo, prašome įvesti slaptažodį du kartus.</p>
        <form action="" method="post">
            <div style="display:none">
                <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
            </div>
            <table>
                <tr>
                    <td>{{ form.new_password1.errors }}
                        <label for="id_new_password1">Naujas slaptažodis:</label></td>
                    <td>{{ form.new_password1 }}</td>
                </tr>
                <tr>
                    <td>{{ form.new_password2.errors }}
                        <label for="id_new_password2">Naujas slaptažodis (pakartoti):</label></td>
                    <td>{{ form.new_password2 }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Keisti slaptažodį" /></td>
                </tr>
            </table>
        </form>
    {% else %}
        <h1>Slaptažodžio pakeisti nepavyko</h1>
        <p>Pateikta nuoroda buvo neteisinga. Prašome pabandyti pakeisti slaptažodį dar kartą.</p>
    {% endif %}
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block title %}Pamiršau slaptažodį{% endblock %}

{% block content %}
<h1>Šaunu!</h1>

<p>
	Tavo el. pašto dėžutėje turbūt jau laukia mūsų išsiųstas laiškelis. Paspausk
	jame esančią nuorodą ir galėsi sukurti naują sąskaitos slaptažodį.
</p>

{% endblock %}

users/templates/users/password_reset_form.html
{% extends "base.html" %}

{% block title %}Pamiršau slaptažodį{% endblock %}

{% block content %}
<h2>Pamiršai slaptažodį?</h2>

<p>
	Nesijaudink! Taip nutinka kiekvienam. Įvesk savo el. pašto adresą ir mes 
	atsiųsime instrukcijas, kaip greitai ir paprastai pakeisti sąskaitos 
	slaptažodį.
</p>

<form action="" method="post">
    <div style="display:none">
        <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
    </div>
     {{ form.email.errors }}
    <p><label for="id_email">El. pašto adresas:</label><br />
    	{{ form.email }}
	</p>
    
    <button type="submit" value="reset-password">Keisti slaptažodį</button>

</form>
{% endblock %}

users/templates/users/siteuser_create.html
{% extends 'base.html' %}

{% block title %}Vartotojo registracija{% endblock %}

{% block content %}
    <h2>Vartotojo registracija</h2>
    <form action="" method="post">
        {% csrf_token %}
		{{ form.id }}
		
		{% if form.errors %}
			<p class="error">
				Vartotojo registracija nepavyko. Atidžiai perskaitykite klaidų pranešimus ir pabandykite dar kartą.
			</p>
		{% endif %}
		
	    {% if form.non_field_errors %}
	        <ul class="error">
	            {% for error in form.non_field_errors %}
	            <li>{{ error }}</li>
	            {% endfor %}
	        </ul>
	    {% endif %}
	    
	    {% if form.field_errors %}
	        <ul class="error">
	            {% for error in form.field_errors %}
	            <li>{{ error }}</li>
	            {% endfor %}
	        </ul>
	    {% endif %}
	    
		
        <p>Privalomi laukeliai yra <span class="required">paryškinti</span>.</p>
        <p>
            <label class="{{ form.username.css_classes }}" for="id_username">{{ form.username.label }}</label><br />
            {{ form.username }}
            {% if form.username.errors %}
                <span class="error">
                    {% for error in form.username.errors %}
                        {{ error }} 
                    {% endfor %}
                </span>
            {% endif %}
            {% if form.username.help_text %}<br /><span class="helptext">{{form.username.help_text }}</span>{% endif %}
        </p>
        <p>
            <label class="{{ form.password.css_classes }}" for="id_password">{{ form.password.label }}</label><br />
            {{ form.password }}
            {% if form.password.errors %}
                <span class="error">
                    {% for error in form.password.errors %}
                        {{ error }}<br />
                    {% endfor %}
                </span>
            {% endif %}
            {% if form.password.help_text %}
            	<br />
            	<span class="helptext">{{form.password.help_text }}</span>
            {% endif %}
        </p>
        <p>
            <label class="{{ form.confirm_password.css_classes }}" for="id_confirm_password">{{ form.confirm_password.label }}</label><br />
            {{ form.confirm_password }}
            {% if form.confirm_password.errors %}
                <span class="error">
                    {% for error in form.confirm_password.errors %}
                        {{ error }} 
                    {% endfor %}
                </span>
            {% endif %}
            {% if form.confirm_password.help_text %}<br /><span class="helptext">{{form.confirm_password.help_text }}</span>{% endif %}
        </p>
        <p>
            <label class="{{ form.email.css_classes }}" for="id_email">{{ form.email.label }}</label><br />
            {{ form.email }}
            {% if form.email.errors %}
                <span class="error">
                    {% for error in form.email.errors %}
                        {{ error }} 
                    {% endfor %}
                </span>
            {% endif %}
            {% if form.email.help_text %}<br /><span class="helptext">{{form.email.help_text }}</span>{% endif %}
        </p>
        <button type="submit" value="Register" >Registruotis</button>
        <a class="cancel" href="/">Atšaukti</a>
    </form>
{% endblock %}

users/templates/users/siteuser_password.html
{% extends 'base.html' %}

{% block title %}Vartotojo registracija{% endblock %}

{% block content %}
    <h2>Keisti slaptažodį</h2>
    <form action="" method="post">
        {% csrf_token %}
		{{ form.id }}
		
		{% if form.errors %}
			<p class="error">
				Vartotojo registracija nepavyko. Atidžiai perskaitykite klaidų pranešimus ir pabandykite dar kartą.
			</p>
		{% endif %}
		
        <p>Privalomi laukeliai yra <span class="required">paryškinti</span>.</p>
        <p>
            <label class="{{ form.old_password.css_classes }}" for="id_old_password">{{ form.old_password.label }}</label><br />
            {{ form.old_password }}
            {% if form.old_password.errors %}
                <span class="error">
                    {% for error in form.old_password.errors %}
                        {{ error }} 
                    {% endfor %}
                </span>
            {% endif %}
            {% if form.old_password.help_text %}<br /><span class="helptext">{{form.old_password.help_text }}</span>{% endif %}
        </p>
        <p>
            <label class="{{ form.new_password1.css_classes }}" for="id_new_password1">{{ form.new_password1.label }}</label><br />
            {{ form.new_password1 }}
            {% if form.new_password1.errors %}
                <span class="error">
                    {% for error in form.new_password1.errors %}
                        {{ error }} 
                    {% endfor %}
                </span>
            {% endif %}
            {% if form.new_password1.help_text %}<br /><span class="helptext">{{form.new_password1.help_text }}</span>{% endif %}
        </p>
        <p>
            <label class="{{ form.new_password2.css_classes }}" for="id_new_password2">{{ form.new_password2.label }}</label><br />
            {{ form.new_password2 }}
            {% if form.new_password2.errors %}
                <span class="error">
                    {% for error in form.new_password2.errors %}
                        {{ error }} 
                    {% endfor %}
                </span>
            {% endif %}
            {% if form.new_password2.help_text %}<br /><span class="helptext">{{form.new_password2.help_text }}</span>{% endif %}
        </p>
        <button type="submit" value="Register" >Keisti slaptažodį</button>
        <a class="cancel" href="/">Atšaukti</a>
    </form>
    
    {% if form.non_field_errors %}
        <ul class="error">
            {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}